#macro UP (keyboard_check_pressed(vk_up) ||  keyboard_check_pressed(ord("W")))
#macro DOWN (keyboard_check_pressed(vk_down) ||  keyboard_check_pressed(ord("S")))
#macro LEFT (keyboard_check_pressed(vk_left) ||  keyboard_check_pressed(ord("A")))
#macro RIGHT (keyboard_check_pressed(vk_right) ||  keyboard_check_pressed(ord("D")))
#macro ENTER (keyboard_check_pressed(vk_enter))
#macro SPACE (keyboard_check_pressed(vk_space))
#macro A (keyboard_check(ord("A")))
#macro D (keyboard_check(ord("D")))
#macro W (keyboard_check(ord("W")))
#macro S (keyboard_check(ord("S")))
#macro isNotMoving (W==0 && A==0 && S==0 && D==0)